Repository aaamoon/copilot-gpt4-service, pull requests merged in 2024-01, with the labels that each got.

#46 增加linux和windows平台通过 github-copilot-cli 一键获取token
  shells/get_copilot_token.bat
  shells/get_copilot_token.sh
Labels: feature

#49 refactor: readme
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/stale.yml
  .github/workflows/build.yml
  .github/workflows/docker_build.yml
  README.md
  README_EN.md
  assets/principle.png
  assets/step1.png
  assets/step1_EN.png
  principle.md
Labels: documentation

#54 通过idea插件获取token
  shells/get_copilot_token.sh
Labels: feature

#74 Added logging
  .gitignore
  Dockerfile
  README.md
  README_EN.md
  config.env.example
  config/config.go
  go.mod
  go.sum
  log/log.go
  main.go
Labels: feature, refactor

#81 refactor: docker build action add version number input
  .github/workflows/docker_build.yml
Labels: action

#85 docs: important notice
  README.md
  README_EN.md
Labels: documentation

#86 chore: add startup notice
  main.go
Labels: documentation

#90 docs: howtouse
  README.md
  README_EN.md
Labels: documentation

#93 fix: update response model and object value
  main.go
Labels: refactor

#134 docs: optimize document formatting
  README.md
  README_CN.md
Labels: documentation

#141 Fix misc
  cache/cache.go
  config/config.go
  log/log.go
  utils/utils.go
Labels: bug, performance

#132 fix: null prefix and suffix
  main.go
Labels: bug, refactor

#159 fix: parse escape characters
  shells/get_copilot_token.sh
Labels: bug

#163 fix: mistake when stream is fale
  main.go
Labels: bug

#156 chore: add Makefile
  Makefile
Labels: chore

#171 fix: headers with different straem
  main.go
Labels: bug

#181 feat: allow users to specify Copilot Token when starting the service
  config/config.go
  docker-compose.yml
  utils/utils.go
Labels: enhancement

#192 fix docker image panic
  Dockerfile
Labels: bug, chore

#185 docs: add support for https
  README.md
  README_CN.md
Labels: documentation

#207 feat: new script to get token
  .gitignore
  README.md
  README_CN.md
  shells/get_copilot_token.py
Labels: enhancement, feature

#213 fix: the return body of completions
  main.go
Labels: bug

#198 ci: speed up docker image build
  .github/workflows/docker_build.yml
  Dockerfile
  cache/cache.go
  go.mod
  go.sum
Labels: action, dependency, performance, test needed

#222 feat: supported cli parameters
  Dockerfile
  config/config.go
Labels: feature

#223 docs: update service deployment instructions
  README.md
  README_CN.md
  config.env.example
  config/config.go
  docker-compose.yml
Labels: documentation

#226 feat: add rate limit per minute
  README.md
  README_CN.md
  config.env.example
  config/config.go
  docker-compose.yml
  go.mod
  go.sum
  main.go
Labels: feature

#229 refactor: invalid route returns 404
  main.go
Labels: refactor

#215 feature: add proxy endpoint for CORS
  README.md
  README_CN.md
  config.env.example
  config/config.go
  main.go
Labels: feature
